---
- name: Create Prometheus file config with owner and permissions
  template:
    src: templates/prometheus/prometheus.yml.j2
    dest: /root/monitoring/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Create rules files with owner and permissions
  template:
    src: "templates/prometheus/rules/{{ item }}.j2"
    dest: "/root/monitoring/prometheus/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ list_rules_files }}"
